{
 "title": "Time_Series",
 "time": { "from": "2012-09-12T18:30:00.000Z", "to": "2020-09-02T18:30:00.000Z" },
 "panels": [
  {
   "title": "Original Data",
   "type": "graph",
   "gridPos": { "h": 22, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamps AS \"time\",\n  value\nFROM \"doc\".\"time\"\nWHERE\n  $__timeFilter(timestamps)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  timestamps AS \"time\",\n  value AS \"Anomaly\"\nFROM \"doc\".\"time\"\nWHERE\n  $__timeFilter(timestamps) AND\n  anomaly = True\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Data",
   "type": "table",
   "gridPos": { "h": 22, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_format('%Y/%m/%d', timestamps) as \"Timestamps\",\n  value as \"Value\",\n  anomaly as \"Anomaly\" \nFROM \"doc\".\"time\"\nORDER BY \"timestamps\""
    }
   ]
  },
  {
   "title": "Predicted Data",
   "type": "graph",
   "gridPos": { "h": 22, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dates AS \"time\",\n  value\nFROM \"doc\".\"predicted\"\nWHERE\n  $__timeFilter(dates)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  dates AS \"time\",\n  value AS \"Anomaly\"\nFROM \"doc\".\"predicted\"\nWHERE\n  anomaly_detected = True\nORDER BY 1"
    }
   ]
  }
 ]
}